version: '3.4'

services:
  tinycrm.api-gateway.api:
    image: ${DOCKER_REGISTRY-}tinycrm.api-gateway.api
    ports:
      - "3000:80"
    build:
      context: .
      dockerfile: TinyCRM/APIGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Routes__0__DownstreamHostAndPorts__0__Host=tinycrm.people.api
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__0__Config__0__Url=http://tinycrm.people.api/swagger/v1/swagger.json
      - Routes__1__DownstreamHostAndPorts__0__Host=tinycrm.sales.api
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__1__Config__0__Url=http://tinycrm.sales.api/swagger/v1/swagger.json
      - Routes__2__DownstreamHostAndPorts__0__Host=tinycrm.iam.api
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__2__Config__0__Url=http://tinycrm.iam.api/swagger/v1/swagger.json
    depends_on:
      - tinycrm.people.api
      - tinycrm.sales.api
      - tinycrm.iam.api
    links:
      - tinycrm.people.api
      - tinycrm.sales.api
      - tinycrm.iam.api
  tinycrm.people.api:
    image: ${DOCKER_REGISTRY-}tinycrm.people.api
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: TinyCRM/Services/People/People.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - GrpcUrls__Identity=http://tinycrm.iam.api:50051
      - ConnectionStrings__Default=Server=tinycrm.db,1433;Database=TinyCrm.People;User=sa;Password=Admin123;TrustServerCertificate=false;Encrypt=false;
      - ConnectionStrings__Redis=tinycrm.redis:6379
      - EventBus__HostName=tinycrm.rabbitmq
    depends_on:
      tinycrm.rabbitmq:
        condition: service_healthy
      tinycrm.sales.api:
        condition: service_started
  tinycrm.sales.api:
    image: ${DOCKER_REGISTRY-}tinycrm.sales.api
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: TinyCRM/Services/Sales/Sales.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - GrpcUrls__Identity=http://tinycrm.iam.api:50051
      - ConnectionStrings__Default=Server=tinycrm.db,1433;Database=TinyCrm.Sales;User=sa;Password=Admin123;TrustServerCertificate=false;Encrypt=false;
      - ConnectionStrings__Redis=tinycrm.redis:6379
      - EventBus__HostName=tinycrm.rabbitmq
    depends_on:
      tinycrm.rabbitmq:
        condition: service_healthy
  tinycrm.iam.api:
    image: ${DOCKER_REGISTRY-}tinycrm.iam.api
    ports:
      - "5003:80"
      - "50051:50051"
    build:
      context: .
      dockerfile: TinyCRM/Services/IAM/IAM.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=grpc://+:50051
      - ConnectionStrings__Default=Server=tinycrm.db,1433;Database=TinyCrm.Iam;User=sa;Password=Admin123;TrustServerCertificate=false;Encrypt=false;
      - ConnectionStrings__Redis=tinycrm.redis:6379
      - JWT__SecretKey=phucphamsieudeptrai
      - Kestrel__Endpoints__Http__Url=http://+:80
      - Kestrel__Endpoints__gRPC__Url=http://+:50051
    restart: always
    depends_on:
      - tinycrm.db
      - tinycrm.redis
  tinycrm.db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "14433:1433"
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
  tinycrm.redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  tinycrm.rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    restart: always
volumes:
  crmdata: