version: '3.4'

services:
  tinycrm.api-gateway.api:
    image: ${DOCKER_REGISTRY-}tinycrm.api-gateway
    ports:
      - "3000:80"
    build:
      context: .
      dockerfile: TinyCRM/APIGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - tinycrm.people.api
      - tinycrm.sales.api
      - tinycrm.iam.api
  tinycrm.people.api:
    image: ${DOCKER_REGISTRY-}tinycrm.people.api
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: TinyCRM/Services/People/People.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      tinycrm.rabbitmq:
        condition: service_healthy
  tinycrm.sales.api:
    image: ${DOCKER_REGISTRY-}tinycrm.sales.api
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: TinyCRM/Services/Sales/Sales.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      tinycrm.rabbitmq:
        condition: service_healthy
  tinycrm.iam.api:
    image: ${DOCKER_REGISTRY-}tinycrm.iam.api
    ports:
      - "5003:80"
    build:
      context: .
      dockerfile: TinyCRM/Services/IAM/IAM.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=Server=tinycrm.db,1433;Database=TinyCrm.Iam;User=sa;Password=Admin123;TrustServerCertificate=false;Encrypt=false;
      - JWT__SecretKey=phucphamsieudeptrai
    restart: always
    depends_on:
      - tinycrm.db
  tinycrm.db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "14433:1433"
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
  tinycrm.rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
volumes:
  crmdata: