# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  tinycrm.api-gateway.api:
    build:
      context: "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend"
      dockerfile: "TinyCRM/APIGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/APIGateway.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
    image: "tinycrm.api-gateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\vieta\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend\\TinyCRM\\APIGateway:/app:rw"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend:/src:rw"
    working_dir: "/app"
  tinycrm.iam.api:
    build:
      context: "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend"
      dockerfile: "TinyCRM/Services/IAM/IAM.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/IAM.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
    image: "tinycrm.iam.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\vieta\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend\\TinyCRM\\Services\\IAM\\IAM.API:/app:rw"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend:/src:rw"
    working_dir: "/app"
  tinycrm.people.api:
    build:
      context: "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend"
      dockerfile: "TinyCRM/Services/People/People.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/People.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
    image: "tinycrm.people.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\vieta\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend\\TinyCRM\\Services\\People\\People.API:/app:rw"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend:/src:rw"
    working_dir: "/app"
  tinycrm.sales.api:
    build:
      context: "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend"
      dockerfile: "TinyCRM/Services/Sales/Sales.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Sales.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\vieta\\.nuget\\packages"
    image: "tinycrm.sales.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\vieta\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend\\TinyCRM\\Services\\Sales\\Sales.API:/app:rw"
    - "D:\\Intern\\Enlab\\.NET\\TinyCRM_Backend:/src:rw"
    working_dir: "/app"
